/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hhkb_animator;

import org.lwjglb.engine.*;
import org.lwjglb.engine.graph.*;
import org.lwjglb.engine.scene.Scene;

public class App
{
    public String getGreeting()
    {
        return "Hello World!";
    }

    public static void main(String[] args)
    {
        System.out.println(new App().getGreeting());
    }
}
